version: "3.2"

services:
  lbh-dynamics365-accesstoken-api:
    image: lbh-dynamics365-accesstoken-api
    build:
      context: lbhDynamics365AccessTokenApi/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Host=dev-database;Port=5432;Database=entitycorex;Username=postgres;Password=mypassword
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: postgres:12
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  lbh-dynamics365-accesstoken-api-test:
    image: lbh-dynamics365-accesstoken-api-test
    build:
      context: .
      dockerfile: lbhDynamics365AccessTokenApi.Tests/Dockerfile
    environment:
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=test-database
    links:
      - test-database
  test-database:
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
